# Makefile.in generated by automake 1.13.4 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2013 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.







am__is_gnu_make = test -n '$(MAKEFILE_LIST)' && test -n '$(MAKELEVEL)'
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/lpcnet
pkgincludedir = $(includedir)/lpcnet
pkglibdir = $(libdir)/lpcnet
pkglibexecdir = $(libexecdir)/lpcnet
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
noinst_PROGRAMS = lpcnet_demo$(EXEEXT) dump_data$(EXEEXT)
subdir = .
DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/Makefile.am \
	$(top_srcdir)/configure $(am__configure_deps) \
	$(srcdir)/config.h.in $(srcdir)/lpcnet.pc.in \
	$(srcdir)/lpcnet-uninstalled.pc.in \
	$(top_srcdir)/doc/Doxyfile.in depcomp $(dist_doc_DATA) \
	$(include_HEADERS) $(noinst_HEADERS) AUTHORS COPYING README \
	config.guess config.sub install-sh missing ltmain.sh
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/attributes.m4 \
	$(top_srcdir)/m4/libtool.m4 $(top_srcdir)/m4/ltoptions.m4 \
	$(top_srcdir)/m4/ltsugar.m4 $(top_srcdir)/m4/ltversion.m4 \
	$(top_srcdir)/m4/lt~obsolete.m4 $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES = lpcnet.pc lpcnet-uninstalled.pc doc/Doxyfile
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(docdir)" \
	"$(DESTDIR)$(pkgconfigdir)" "$(DESTDIR)$(includedir)"
LTLIBRARIES = $(lib_LTLIBRARIES)
am__DEPENDENCIES_1 =
liblpcnet_la_DEPENDENCIES = $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1)
am__dirstamp = $(am__leading_dot)dirstamp
am_liblpcnet_la_OBJECTS = src/common.lo src/lpcnet.lo \
	src/lpcnet_dec.lo src/lpcnet_enc.lo src/nnet.lo \
	src/nnet_data.lo src/ceps_codebooks.lo src/pitch.lo \
	src/freq.lo src/kiss_fft.lo src/celt_lpc.lo
liblpcnet_la_OBJECTS = $(am_liblpcnet_la_OBJECTS)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
liblpcnet_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(liblpcnet_la_LDFLAGS) $(LDFLAGS) -o $@
PROGRAMS = $(noinst_PROGRAMS)
am_dump_data_OBJECTS = src/dump_data-common.$(OBJEXT) \
	src/dump_data-dump_data.$(OBJEXT) src/dump_data-freq.$(OBJEXT) \
	src/dump_data-kiss_fft.$(OBJEXT) src/dump_data-pitch.$(OBJEXT) \
	src/dump_data-celt_lpc.$(OBJEXT) \
	src/dump_data-lpcnet_dec.$(OBJEXT) \
	src/dump_data-lpcnet_enc.$(OBJEXT) \
	src/dump_data-ceps_codebooks.$(OBJEXT)
dump_data_OBJECTS = $(am_dump_data_OBJECTS)
dump_data_DEPENDENCIES = $(am__DEPENDENCIES_1)
dump_data_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(dump_data_CFLAGS) \
	$(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
am_lpcnet_demo_OBJECTS = src/lpcnet_demo.$(OBJEXT)
lpcnet_demo_OBJECTS = $(am_lpcnet_demo_OBJECTS)
lpcnet_demo_DEPENDENCIES = liblpcnet.la
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(liblpcnet_la_SOURCES) $(dump_data_SOURCES) \
	$(lpcnet_demo_SOURCES)
DIST_SOURCES = $(liblpcnet_la_SOURCES) $(dump_data_SOURCES) \
	$(lpcnet_demo_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
DATA = $(dist_doc_DATA) $(pkgconfig_DATA)
HEADERS = $(include_HEADERS) $(noinst_HEADERS)
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz $(distdir).zip
GZIP_ENV = --best
DIST_TARGETS = dist-gzip dist-zip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /ssd4/exec/yins/work/vocoders/LPCNet_Bunched_V2/missing aclocal-1.13
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 0
AR = ar
AUTOCONF = ${SHELL} /ssd4/exec/yins/work/vocoders/LPCNet_Bunched_V2/missing autoconf
AUTOHEADER = ${SHELL} /ssd4/exec/yins/work/vocoders/LPCNet_Bunched_V2/missing autoheader
AUTOMAKE = ${SHELL} /ssd4/exec/yins/work/vocoders/LPCNet_Bunched_V2/missing automake-1.13
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -O3 -g -mavx2 -mfma -pedantic -Wall -Wextra -Wno-sign-compare -Wno-parentheses -Wno-long-long -fvisibility=hidden
CPP = gcc -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
FGREP = /usr/bin/grep -F
GREP = /usr/bin/grep
HAVE_DOT = no
HAVE_DOXYGEN = no
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = 
LIBM = -lm
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
LT_SYS_LIBRARY_PATH = 
MAINT = 
MAKEINFO = ${SHELL} /ssd4/exec/yins/work/vocoders/LPCNet_Bunched_V2/missing makeinfo
MANIFEST_TOOL = :
MKDIR_P = /usr/bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OP_LT_AGE = 0
OP_LT_CURRENT = 0
OP_LT_REVISION = 0
OTOOL = 
OTOOL64 = 
PACKAGE = lpcnet
PACKAGE_BUGREPORT = jmvalin@jmvalin.ca
PACKAGE_NAME = lpcnet
PACKAGE_STRING = lpcnet unknown
PACKAGE_TARNAME = lpcnet
PACKAGE_URL = 
PACKAGE_VERSION = unknown
PATH_SEPARATOR = :
RANLIB = ranlib
SED = /usr/bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = unknown
abs_builddir = /ssd4/exec/yins/work/vocoders/LPCNet_Bunched_V2
abs_srcdir = /ssd4/exec/yins/work/vocoders/LPCNet_Bunched_V2
abs_top_builddir = /ssd4/exec/yins/work/vocoders/LPCNet_Bunched_V2
abs_top_srcdir = /ssd4/exec/yins/work/vocoders/LPCNet_Bunched_V2
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /ssd4/exec/yins/work/vocoders/LPCNet_Bunched_V2/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
lrintf_lib = 
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
ACLOCAL_AMFLAGS = -I m4
AM_CFLAGS = -I$(top_srcdir)/include $(DEPS_CFLAGS)
dist_doc_DATA = COPYING AUTHORS README README.md
include_HEADERS = include/lpcnet.h
lib_LTLIBRARIES = liblpcnet.la
noinst_HEADERS = src/arch.h  \
		 src/celt_lpc.h  \
		 src/common.h  \
		 src/freq.h  \
		 src/_kiss_fft_guts.h  \
		 src/kiss_fft.h  \
		 src/lpcnet_private.h \
		 src/opus_types.h  \
		 src/nnet_data.h  \
		 src/nnet.h  \
		 src/pitch.h  \
		 src/tansig_table.h \
		 src/vec.h \
		 src/vec_avx.h \
		 src/vec_neon.h

liblpcnet_la_SOURCES = \
	src/common.c \
	src/lpcnet.c \
	src/lpcnet_dec.c \
	src/lpcnet_enc.c \
	src/nnet.c \
	src/nnet_data.c \
	src/ceps_codebooks.c \
	src/pitch.c \
	src/freq.c \
	src/kiss_fft.c \
	src/celt_lpc.c

liblpcnet_la_LIBADD = $(DEPS_LIBS) $(lrintf_lib) $(LIBM)
liblpcnet_la_LDFLAGS = -no-undefined \
 -version-info 0:0:0

lpcnet_demo_SOURCES = src/lpcnet_demo.c
lpcnet_demo_LDADD = liblpcnet.la

#DUMP_SOURCES = src/freq.c src/kiss_fft.c src/pitch.c src/celt_lpc.c src/lpcnet_dec.c src/lpcnet_enc.c src/ceps_codebooks.c src/common.c
#DUMP_OBJ = $(DUMP_SOURCES:.c=.lo)
#dump_data_SOURCES = src/dump_data.c
#dump_data_LDADD = $(DUMP_OBJ) $(LIBM)
dump_data_SOURCES = src/common.c src/dump_data.c src/freq.c src/kiss_fft.c src/pitch.c src/celt_lpc.c src/lpcnet_dec.c src/lpcnet_enc.c src/ceps_codebooks.c
dump_data_LDADD = $(LIBM)
dump_data_CFLAGS = $(AM_CFLAGS)
pkgconfigdir = $(libdir)/pkgconfig
pkgconfig_DATA = lpcnet.pc
EXTRA_DIST = \
 lpcnet.pc.in \
 lpcnet-uninstalled.pc.in \
 doc/Doxyfile.in \
 doc/Makefile

all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@if test ! -f $@; then rm -f stamp-h1; else :; fi
	@if test ! -f $@; then $(MAKE) $(AM_MAKEFLAGS) stamp-h1; else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
lpcnet.pc: $(top_builddir)/config.status $(srcdir)/lpcnet.pc.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
lpcnet-uninstalled.pc: $(top_builddir)/config.status $(srcdir)/lpcnet-uninstalled.pc.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
doc/Doxyfile: $(top_builddir)/config.status $(top_srcdir)/doc/Doxyfile.in
	cd $(top_builddir) && $(SHELL) ./config.status $@

install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(MKDIR_P) '$(DESTDIR)$(libdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(libdir)" || exit 1; \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(libdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(libdir)"; \
	}

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$f"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; \
	locs=`for p in $$list; do echo $$p; done | \
	      sed 's|^[^/]*$$|.|; s|/[^/]*$$||; s|$$|/so_locations|' | \
	      sort -u`; \
	test -z "$$locs" || { \
	  echo rm -f $${locs}; \
	  rm -f $${locs}; \
	}
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: > src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/$(DEPDIR)
	@: > src/$(DEPDIR)/$(am__dirstamp)
src/common.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/lpcnet.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/lpcnet_dec.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/lpcnet_enc.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/nnet.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/nnet_data.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/ceps_codebooks.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/pitch.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/freq.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/kiss_fft.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/celt_lpc.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)

liblpcnet.la: $(liblpcnet_la_OBJECTS) $(liblpcnet_la_DEPENDENCIES) $(EXTRA_liblpcnet_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(liblpcnet_la_LINK) -rpath $(libdir) $(liblpcnet_la_OBJECTS) $(liblpcnet_la_LIBADD) $(LIBS)

clean-noinstPROGRAMS:
	@list='$(noinst_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
src/dump_data-common.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/dump_data-dump_data.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/dump_data-freq.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/dump_data-kiss_fft.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/dump_data-pitch.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/dump_data-celt_lpc.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/dump_data-lpcnet_dec.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/dump_data-lpcnet_enc.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/dump_data-ceps_codebooks.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

dump_data$(EXEEXT): $(dump_data_OBJECTS) $(dump_data_DEPENDENCIES) $(EXTRA_dump_data_DEPENDENCIES) 
	@rm -f dump_data$(EXEEXT)
	$(AM_V_CCLD)$(dump_data_LINK) $(dump_data_OBJECTS) $(dump_data_LDADD) $(LIBS)
src/lpcnet_demo.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

lpcnet_demo$(EXEEXT): $(lpcnet_demo_OBJECTS) $(lpcnet_demo_DEPENDENCIES) $(EXTRA_lpcnet_demo_DEPENDENCIES) 
	@rm -f lpcnet_demo$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(lpcnet_demo_OBJECTS) $(lpcnet_demo_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/*.$(OBJEXT)
	-rm -f src/*.lo

distclean-compile:
	-rm -f *.tab.c

include src/$(DEPDIR)/celt_lpc.Plo
include src/$(DEPDIR)/ceps_codebooks.Plo
include src/$(DEPDIR)/common.Plo
include src/$(DEPDIR)/dump_data-celt_lpc.Po
include src/$(DEPDIR)/dump_data-ceps_codebooks.Po
include src/$(DEPDIR)/dump_data-common.Po
include src/$(DEPDIR)/dump_data-dump_data.Po
include src/$(DEPDIR)/dump_data-freq.Po
include src/$(DEPDIR)/dump_data-kiss_fft.Po
include src/$(DEPDIR)/dump_data-lpcnet_dec.Po
include src/$(DEPDIR)/dump_data-lpcnet_enc.Po
include src/$(DEPDIR)/dump_data-pitch.Po
include src/$(DEPDIR)/freq.Plo
include src/$(DEPDIR)/kiss_fft.Plo
include src/$(DEPDIR)/lpcnet.Plo
include src/$(DEPDIR)/lpcnet_dec.Plo
include src/$(DEPDIR)/lpcnet_demo.Po
include src/$(DEPDIR)/lpcnet_enc.Plo
include src/$(DEPDIR)/nnet.Plo
include src/$(DEPDIR)/nnet_data.Plo
include src/$(DEPDIR)/pitch.Plo

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.c.lo:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CC)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LTCOMPILE) -c -o $@ $<

src/dump_data-common.o: src/common.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -MT src/dump_data-common.o -MD -MP -MF src/$(DEPDIR)/dump_data-common.Tpo -c -o src/dump_data-common.o `test -f 'src/common.c' || echo '$(srcdir)/'`src/common.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/dump_data-common.Tpo src/$(DEPDIR)/dump_data-common.Po
#	$(AM_V_CC)source='src/common.c' object='src/dump_data-common.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -c -o src/dump_data-common.o `test -f 'src/common.c' || echo '$(srcdir)/'`src/common.c

src/dump_data-common.obj: src/common.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -MT src/dump_data-common.obj -MD -MP -MF src/$(DEPDIR)/dump_data-common.Tpo -c -o src/dump_data-common.obj `if test -f 'src/common.c'; then $(CYGPATH_W) 'src/common.c'; else $(CYGPATH_W) '$(srcdir)/src/common.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/dump_data-common.Tpo src/$(DEPDIR)/dump_data-common.Po
#	$(AM_V_CC)source='src/common.c' object='src/dump_data-common.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -c -o src/dump_data-common.obj `if test -f 'src/common.c'; then $(CYGPATH_W) 'src/common.c'; else $(CYGPATH_W) '$(srcdir)/src/common.c'; fi`

src/dump_data-dump_data.o: src/dump_data.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -MT src/dump_data-dump_data.o -MD -MP -MF src/$(DEPDIR)/dump_data-dump_data.Tpo -c -o src/dump_data-dump_data.o `test -f 'src/dump_data.c' || echo '$(srcdir)/'`src/dump_data.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/dump_data-dump_data.Tpo src/$(DEPDIR)/dump_data-dump_data.Po
#	$(AM_V_CC)source='src/dump_data.c' object='src/dump_data-dump_data.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -c -o src/dump_data-dump_data.o `test -f 'src/dump_data.c' || echo '$(srcdir)/'`src/dump_data.c

src/dump_data-dump_data.obj: src/dump_data.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -MT src/dump_data-dump_data.obj -MD -MP -MF src/$(DEPDIR)/dump_data-dump_data.Tpo -c -o src/dump_data-dump_data.obj `if test -f 'src/dump_data.c'; then $(CYGPATH_W) 'src/dump_data.c'; else $(CYGPATH_W) '$(srcdir)/src/dump_data.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/dump_data-dump_data.Tpo src/$(DEPDIR)/dump_data-dump_data.Po
#	$(AM_V_CC)source='src/dump_data.c' object='src/dump_data-dump_data.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -c -o src/dump_data-dump_data.obj `if test -f 'src/dump_data.c'; then $(CYGPATH_W) 'src/dump_data.c'; else $(CYGPATH_W) '$(srcdir)/src/dump_data.c'; fi`

src/dump_data-freq.o: src/freq.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -MT src/dump_data-freq.o -MD -MP -MF src/$(DEPDIR)/dump_data-freq.Tpo -c -o src/dump_data-freq.o `test -f 'src/freq.c' || echo '$(srcdir)/'`src/freq.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/dump_data-freq.Tpo src/$(DEPDIR)/dump_data-freq.Po
#	$(AM_V_CC)source='src/freq.c' object='src/dump_data-freq.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -c -o src/dump_data-freq.o `test -f 'src/freq.c' || echo '$(srcdir)/'`src/freq.c

src/dump_data-freq.obj: src/freq.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -MT src/dump_data-freq.obj -MD -MP -MF src/$(DEPDIR)/dump_data-freq.Tpo -c -o src/dump_data-freq.obj `if test -f 'src/freq.c'; then $(CYGPATH_W) 'src/freq.c'; else $(CYGPATH_W) '$(srcdir)/src/freq.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/dump_data-freq.Tpo src/$(DEPDIR)/dump_data-freq.Po
#	$(AM_V_CC)source='src/freq.c' object='src/dump_data-freq.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -c -o src/dump_data-freq.obj `if test -f 'src/freq.c'; then $(CYGPATH_W) 'src/freq.c'; else $(CYGPATH_W) '$(srcdir)/src/freq.c'; fi`

src/dump_data-kiss_fft.o: src/kiss_fft.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -MT src/dump_data-kiss_fft.o -MD -MP -MF src/$(DEPDIR)/dump_data-kiss_fft.Tpo -c -o src/dump_data-kiss_fft.o `test -f 'src/kiss_fft.c' || echo '$(srcdir)/'`src/kiss_fft.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/dump_data-kiss_fft.Tpo src/$(DEPDIR)/dump_data-kiss_fft.Po
#	$(AM_V_CC)source='src/kiss_fft.c' object='src/dump_data-kiss_fft.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -c -o src/dump_data-kiss_fft.o `test -f 'src/kiss_fft.c' || echo '$(srcdir)/'`src/kiss_fft.c

src/dump_data-kiss_fft.obj: src/kiss_fft.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -MT src/dump_data-kiss_fft.obj -MD -MP -MF src/$(DEPDIR)/dump_data-kiss_fft.Tpo -c -o src/dump_data-kiss_fft.obj `if test -f 'src/kiss_fft.c'; then $(CYGPATH_W) 'src/kiss_fft.c'; else $(CYGPATH_W) '$(srcdir)/src/kiss_fft.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/dump_data-kiss_fft.Tpo src/$(DEPDIR)/dump_data-kiss_fft.Po
#	$(AM_V_CC)source='src/kiss_fft.c' object='src/dump_data-kiss_fft.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -c -o src/dump_data-kiss_fft.obj `if test -f 'src/kiss_fft.c'; then $(CYGPATH_W) 'src/kiss_fft.c'; else $(CYGPATH_W) '$(srcdir)/src/kiss_fft.c'; fi`

src/dump_data-pitch.o: src/pitch.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -MT src/dump_data-pitch.o -MD -MP -MF src/$(DEPDIR)/dump_data-pitch.Tpo -c -o src/dump_data-pitch.o `test -f 'src/pitch.c' || echo '$(srcdir)/'`src/pitch.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/dump_data-pitch.Tpo src/$(DEPDIR)/dump_data-pitch.Po
#	$(AM_V_CC)source='src/pitch.c' object='src/dump_data-pitch.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -c -o src/dump_data-pitch.o `test -f 'src/pitch.c' || echo '$(srcdir)/'`src/pitch.c

src/dump_data-pitch.obj: src/pitch.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -MT src/dump_data-pitch.obj -MD -MP -MF src/$(DEPDIR)/dump_data-pitch.Tpo -c -o src/dump_data-pitch.obj `if test -f 'src/pitch.c'; then $(CYGPATH_W) 'src/pitch.c'; else $(CYGPATH_W) '$(srcdir)/src/pitch.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/dump_data-pitch.Tpo src/$(DEPDIR)/dump_data-pitch.Po
#	$(AM_V_CC)source='src/pitch.c' object='src/dump_data-pitch.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -c -o src/dump_data-pitch.obj `if test -f 'src/pitch.c'; then $(CYGPATH_W) 'src/pitch.c'; else $(CYGPATH_W) '$(srcdir)/src/pitch.c'; fi`

src/dump_data-celt_lpc.o: src/celt_lpc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -MT src/dump_data-celt_lpc.o -MD -MP -MF src/$(DEPDIR)/dump_data-celt_lpc.Tpo -c -o src/dump_data-celt_lpc.o `test -f 'src/celt_lpc.c' || echo '$(srcdir)/'`src/celt_lpc.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/dump_data-celt_lpc.Tpo src/$(DEPDIR)/dump_data-celt_lpc.Po
#	$(AM_V_CC)source='src/celt_lpc.c' object='src/dump_data-celt_lpc.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -c -o src/dump_data-celt_lpc.o `test -f 'src/celt_lpc.c' || echo '$(srcdir)/'`src/celt_lpc.c

src/dump_data-celt_lpc.obj: src/celt_lpc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -MT src/dump_data-celt_lpc.obj -MD -MP -MF src/$(DEPDIR)/dump_data-celt_lpc.Tpo -c -o src/dump_data-celt_lpc.obj `if test -f 'src/celt_lpc.c'; then $(CYGPATH_W) 'src/celt_lpc.c'; else $(CYGPATH_W) '$(srcdir)/src/celt_lpc.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/dump_data-celt_lpc.Tpo src/$(DEPDIR)/dump_data-celt_lpc.Po
#	$(AM_V_CC)source='src/celt_lpc.c' object='src/dump_data-celt_lpc.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -c -o src/dump_data-celt_lpc.obj `if test -f 'src/celt_lpc.c'; then $(CYGPATH_W) 'src/celt_lpc.c'; else $(CYGPATH_W) '$(srcdir)/src/celt_lpc.c'; fi`

src/dump_data-lpcnet_dec.o: src/lpcnet_dec.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -MT src/dump_data-lpcnet_dec.o -MD -MP -MF src/$(DEPDIR)/dump_data-lpcnet_dec.Tpo -c -o src/dump_data-lpcnet_dec.o `test -f 'src/lpcnet_dec.c' || echo '$(srcdir)/'`src/lpcnet_dec.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/dump_data-lpcnet_dec.Tpo src/$(DEPDIR)/dump_data-lpcnet_dec.Po
#	$(AM_V_CC)source='src/lpcnet_dec.c' object='src/dump_data-lpcnet_dec.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -c -o src/dump_data-lpcnet_dec.o `test -f 'src/lpcnet_dec.c' || echo '$(srcdir)/'`src/lpcnet_dec.c

src/dump_data-lpcnet_dec.obj: src/lpcnet_dec.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -MT src/dump_data-lpcnet_dec.obj -MD -MP -MF src/$(DEPDIR)/dump_data-lpcnet_dec.Tpo -c -o src/dump_data-lpcnet_dec.obj `if test -f 'src/lpcnet_dec.c'; then $(CYGPATH_W) 'src/lpcnet_dec.c'; else $(CYGPATH_W) '$(srcdir)/src/lpcnet_dec.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/dump_data-lpcnet_dec.Tpo src/$(DEPDIR)/dump_data-lpcnet_dec.Po
#	$(AM_V_CC)source='src/lpcnet_dec.c' object='src/dump_data-lpcnet_dec.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -c -o src/dump_data-lpcnet_dec.obj `if test -f 'src/lpcnet_dec.c'; then $(CYGPATH_W) 'src/lpcnet_dec.c'; else $(CYGPATH_W) '$(srcdir)/src/lpcnet_dec.c'; fi`

src/dump_data-lpcnet_enc.o: src/lpcnet_enc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -MT src/dump_data-lpcnet_enc.o -MD -MP -MF src/$(DEPDIR)/dump_data-lpcnet_enc.Tpo -c -o src/dump_data-lpcnet_enc.o `test -f 'src/lpcnet_enc.c' || echo '$(srcdir)/'`src/lpcnet_enc.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/dump_data-lpcnet_enc.Tpo src/$(DEPDIR)/dump_data-lpcnet_enc.Po
#	$(AM_V_CC)source='src/lpcnet_enc.c' object='src/dump_data-lpcnet_enc.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -c -o src/dump_data-lpcnet_enc.o `test -f 'src/lpcnet_enc.c' || echo '$(srcdir)/'`src/lpcnet_enc.c

src/dump_data-lpcnet_enc.obj: src/lpcnet_enc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -MT src/dump_data-lpcnet_enc.obj -MD -MP -MF src/$(DEPDIR)/dump_data-lpcnet_enc.Tpo -c -o src/dump_data-lpcnet_enc.obj `if test -f 'src/lpcnet_enc.c'; then $(CYGPATH_W) 'src/lpcnet_enc.c'; else $(CYGPATH_W) '$(srcdir)/src/lpcnet_enc.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/dump_data-lpcnet_enc.Tpo src/$(DEPDIR)/dump_data-lpcnet_enc.Po
#	$(AM_V_CC)source='src/lpcnet_enc.c' object='src/dump_data-lpcnet_enc.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -c -o src/dump_data-lpcnet_enc.obj `if test -f 'src/lpcnet_enc.c'; then $(CYGPATH_W) 'src/lpcnet_enc.c'; else $(CYGPATH_W) '$(srcdir)/src/lpcnet_enc.c'; fi`

src/dump_data-ceps_codebooks.o: src/ceps_codebooks.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -MT src/dump_data-ceps_codebooks.o -MD -MP -MF src/$(DEPDIR)/dump_data-ceps_codebooks.Tpo -c -o src/dump_data-ceps_codebooks.o `test -f 'src/ceps_codebooks.c' || echo '$(srcdir)/'`src/ceps_codebooks.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/dump_data-ceps_codebooks.Tpo src/$(DEPDIR)/dump_data-ceps_codebooks.Po
#	$(AM_V_CC)source='src/ceps_codebooks.c' object='src/dump_data-ceps_codebooks.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -c -o src/dump_data-ceps_codebooks.o `test -f 'src/ceps_codebooks.c' || echo '$(srcdir)/'`src/ceps_codebooks.c

src/dump_data-ceps_codebooks.obj: src/ceps_codebooks.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -MT src/dump_data-ceps_codebooks.obj -MD -MP -MF src/$(DEPDIR)/dump_data-ceps_codebooks.Tpo -c -o src/dump_data-ceps_codebooks.obj `if test -f 'src/ceps_codebooks.c'; then $(CYGPATH_W) 'src/ceps_codebooks.c'; else $(CYGPATH_W) '$(srcdir)/src/ceps_codebooks.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/dump_data-ceps_codebooks.Tpo src/$(DEPDIR)/dump_data-ceps_codebooks.Po
#	$(AM_V_CC)source='src/ceps_codebooks.c' object='src/dump_data-ceps_codebooks.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(dump_data_CFLAGS) $(CFLAGS) -c -o src/dump_data-ceps_codebooks.obj `if test -f 'src/ceps_codebooks.c'; then $(CYGPATH_W) 'src/ceps_codebooks.c'; else $(CYGPATH_W) '$(srcdir)/src/ceps_codebooks.c'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs
	-rm -rf src/.libs src/_libs

distclean-libtool:
	-rm -f libtool config.lt
install-dist_docDATA: $(dist_doc_DATA)
	@$(NORMAL_INSTALL)
	@list='$(dist_doc_DATA)'; test -n "$(docdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(docdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(docdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(docdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(docdir)" || exit $$?; \
	done

uninstall-dist_docDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(dist_doc_DATA)'; test -n "$(docdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(docdir)'; $(am__uninstall_files_from_dir)
install-pkgconfigDATA: $(pkgconfig_DATA)
	@$(NORMAL_INSTALL)
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(pkgconfigdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(pkgconfigdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(pkgconfigdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(pkgconfigdir)" || exit $$?; \
	done

uninstall-pkgconfigDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(pkgconfigdir)'; $(am__uninstall_files_from_dir)
install-includeHEADERS: $(include_HEADERS)
	@$(NORMAL_INSTALL)
	@list='$(include_HEADERS)'; test -n "$(includedir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(includedir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(includedir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_HEADER) $$files '$(DESTDIR)$(includedir)'"; \
	  $(INSTALL_HEADER) $$files "$(DESTDIR)$(includedir)" || exit $$?; \
	done

uninstall-includeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(include_HEADERS)'; test -n "$(includedir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(includedir)'; $(am__uninstall_files_from_dir)

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	$(MAKE) $(AM_MAKEFLAGS) \
	  top_distdir="$(top_distdir)" distdir="$(distdir)" \
	  dist-hook
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)
dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-local:
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(DATA) $(HEADERS) \
		config.h all-local
installdirs:
	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(docdir)" "$(DESTDIR)$(pkgconfigdir)" "$(DESTDIR)$(includedir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f src/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
uninstall-local:
install-data-local:
clean-local:
clean: clean-am

clean-am: clean-generic clean-libLTLIBRARIES clean-libtool clean-local \
	clean-noinstPROGRAMS mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf src/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-data-local install-dist_docDATA \
	install-includeHEADERS install-pkgconfigDATA

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-libLTLIBRARIES

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf src/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-dist_docDATA uninstall-includeHEADERS \
	uninstall-libLTLIBRARIES uninstall-local \
	uninstall-pkgconfigDATA

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am all-local am--refresh check \
	check-am clean clean-cscope clean-generic clean-libLTLIBRARIES \
	clean-libtool clean-local clean-noinstPROGRAMS cscope \
	cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-hook dist-lzip dist-shar dist-tarZ dist-xz \
	dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-libtool \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-data install-data-am install-data-local \
	install-dist_docDATA install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am \
	install-includeHEADERS install-info install-info-am \
	install-libLTLIBRARIES install-man install-pdf install-pdf-am \
	install-pkgconfigDATA install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags tags-am uninstall uninstall-am uninstall-dist_docDATA \
	uninstall-includeHEADERS uninstall-libLTLIBRARIES \
	uninstall-local uninstall-pkgconfigDATA


debug:
	$(MAKE) CFLAGS="${CFLAGS} -O0 -ggdb -DOP_ENABLE_ASSERTIONS" all

# Targets to build and install just the library without the docs
liblpcnet install-liblpcnet: NO_DOXYGEN = 1

lpcnet: all
install-lpcnet: install

# Or just the docs
docs: doc/doxygen-build.stamp

install-docs:
	@if [ -z "$(NO_DOXYGEN)" ]; then \
	  ( cd doc && \
	    echo "Installing documentation in $(DESTDIR)$(docdir)"; \
	    $(INSTALL) -d $(DESTDIR)$(docdir)/html/search; \
	    for f in `find html -type f \! -name "installdox"` ; do \
	      $(INSTALL_DATA) $$f $(DESTDIR)$(docdir)/$$f;     \
	    done ) \
	fi

doc/doxygen-build.stamp: doc/Doxyfile \
                         $(top_srcdir)/include/*.h
	@[ -n "$(NO_DOXYGEN)" ] || ( cd doc && doxygen && touch $(@F) )

# Or everything (by default)
#all-local: docs

#install-data-local: install-docs

#clean-local:
#	$(RM) -r doc/html
#	$(RM) -r doc/latex
#	$(RM) doc/doxygen-build.stamp

#uninstall-local:
#	$(RM) -r $(DESTDIR)$(docdir)/html

# We check this every time make is run, with configure.ac being touched to
# trigger an update of the build system files if update_version changes the
# current PACKAGE_VERSION (or if package_version was modified manually by a
# user with either AUTO_UPDATE=no or no update_version script present - the
# latter being the normal case for tarball releases).
#
# We can't just add the package_version file to CONFIGURE_DEPENDENCIES since
# simply running autoconf will not actually regenerate configure for us when
# the content of that file changes (due to autoconf dependency checking not
# knowing about that without us creating yet another file for it to include).
#
# The MAKECMDGOALS check is a gnu-make'ism, but will degrade 'gracefully' for
# makes that don't support it.  The only loss of functionality is not forcing
# an update of package_version for `make dist` if AUTO_UPDATE=no, but that is
# unlikely to be a real problem for any real user.
$(top_srcdir)/configure.ac: force
	@case "$(MAKECMDGOALS)" in \
	    dist-hook)                             exit 0       ;; \
	    dist-* | dist | distcheck | distclean) _arg=release ;; \
	esac; \
	if ! $(top_srcdir)/update_version $$_arg 2> /dev/null; then \
	    if [ ! -e $(top_srcdir)/package_version ]; then \
		echo 'PACKAGE_VERSION="unknown"' > $(top_srcdir)/package_version; \
	    fi; \
	    . $(top_srcdir)/package_version || exit 1; \
	    [ "$(PACKAGE_VERSION)" != "$$PACKAGE_VERSION" ] || exit 0; \
	fi; \
	touch $@

force:

# Create a minimal package_version file when make dist is run.
dist-hook:
	echo 'PACKAGE_VERSION="$(PACKAGE_VERSION)"' > $(top_distdir)/package_version

.PHONY: lpcnet install-lpcnet docs install-docs

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
